version = 0.1

[default.deploy.parameters]
stack_name = "motorcycle-repair-shop"
resolve_s3 = true
s3_prefix = "motorcycle-repair-shop"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\" DBUrl=\"https://toklwbqrgqsgaovzleev.supabase.co\" DBKey=\"sb_publishable_9ToFd0mY6_QhXaGecuwxQA_ixnC9hQ0\" LogRetentionDays=\"14\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
