AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend en Python con Lambdas y API Gateway

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    MemorySize: 256

Parameters:
  Environment:
    Type: String
    Default: dev
  DBUrl:
    Type: String
    Default: https://ezmzjivappfgenfygsqg.supabase.co
  DBKey:
    Type: String
    Default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bXpqaXZhcHBmZ2VuZnlnc3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTgyMzAsImV4cCI6MjA3MDk5NDIzMH0.CS_4_lZhO6aTDA8LO03vNBgikEaYO0aN1ZREvs6F88k


Resources:

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: "Shared utilities for Lambdas"
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
      BuildProperties:
        PIP_REQUIREMENTS: requirements.txt

  GetCustomersApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetCustomersApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/customers/lambdas/get_customers
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /customers
            Method: get

  AddCustomerApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AddCustomerApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/customers/lambdas/add_customer
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /customers
            Method: post

  GetMechanicsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetMechanicsApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/mechanics/lambdas/get_mechanics
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mechanics
            Method: get

  AddMechanicApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AddMechanicApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/mechanics/lambdas/add_mechanic
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mechanics
            Method: post

  GetProductsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetProductsApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/products/lambdas/get_products
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /products
            Method: get

  GetProductByIdApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetProductByIdApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/products/lambdas/get_product_by_id
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /products/searchById
            Method: get

  AddProductApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AddProductApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/products/lambdas/add_product
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /products
            Method: post

  GetSuppliersApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetSuppliersApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/suppliers/lambdas/get_suppliers
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /suppliers
            Method: get

  AddSupplierApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AddSupplierApi-${Environment}"
      Layers:
        - !Ref SharedLayer
      CodeUri: src/domains/suppliers/lambdas/add_supplier
      Handler: main.lambda_handler
      Environment:
        Variables:
          DB_URL: !Ref DBUrl
          DB_KEY: !Ref DBKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /suppliers
            Method: post
